DROP TABLE IF EXISTS CC_CURRENCY_MASTER;

CREATE TABLE CC_CURRENCY_MASTER (
  id SERIAL PRIMARY KEY,
  code VARCHAR(5) NOT NULL,
  name VARCHAR(64) NOT NULL
);

DROP TABLE IF EXISTS CC_CURRENCY_RATES_MASTER;

CREATE TABLE CC_CURRENCY_RATES_MASTER (
  id SERIAL PRIMARY KEY,
  from_currency INT NOT NULL,
  to_currency INT NOT NULL,
  rate real NOT NULL
);